// <auto-generated />
using System;
using BrazilEconomicMonitor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrazilEconomicMonitor.Migrations
{
    [DbContext(typeof(BrazilEconomicMonitorDbContext))]
    [Migration("20260905124925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "ObservationDate")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRaw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Code")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Sources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Observation", b =>
                {
                    b.HasOne("BrazilEconomicMonitor.Domain.Entities.Series", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Series", b =>
                {
                    b.HasOne("BrazilEconomicMonitor.Domain.Entities.Sources", "Sources")
                        .WithMany("Series")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Series", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("BrazilEconomicMonitor.Domain.Entities.Sources", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
